---
global:
  image:
    tag: "v2.14.2"

dex:
  enabled: false

server:
  extraArgs:
    - --insecure

configs:
  secret:
    argocdServerAdminPassword: "$2y$10$Y8QR5nZtcxVfJpxqlunDYO1msjxJ848a2t/vRwnfBqBhx27azUC7i"
  cm:
    application.resourceTrackingMethod: annotation+label