apiVersion: v1
kind: Secret
metadata:
  name: private-repo-bdk
  namespace: gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:owshq-plumbers/trn-mst-bdk-2-0.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCl+d3zWKEhCM4UlRg/PbDCYtI35RHzfy4Gnu1w1bfp4QAAAJhXMxwNVzMc
    DQAAAAtzc2gtZWQyNTUxOQAAACCl+d3zWKEhCM4UlRg/PbDCYtI35RHzfy4Gnu1w1bfp4Q
    AAAEAFMcM5gVndlj3Qf93xliAc4N47vrdcqZI5lzbQtBoacKX53fNYoSEIzhSVGD89sMJi
    0jflEfN/Lgae7XDVt+nhAAAAEnZpY3RvckBibGFja2RyYWdvbgECAw==
    -----END OPENSSH PRIVATE KEY-----
  