{
 "title": "Flink Dashboard",
 "description": "Dashboard for Job Manager and Task Manager, prepared for versions: 1.12.X, 1.13.X",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Source", "query": "prometheus" },
   { "name": "tm_id", "label": "Task Manager", "query": { "query": "label_values(tm_id)" } },
   {
    "name": "jm_instance",
    "label": "Job Manager",
    "query": {
     "query": "label_values(flink_k8soperator_numRegisteredTaskManagers,instance)"
    }
   },
   {
    "name": "job_name",
    "label": "Job Name",
    "query": {
     "query": "label_values(flink_taskmanager_job_task_isBackPressured{tm_id=~\"$tm_id\"},job_name)"
    }
   },
   {
    "name": "task_name",
    "label": "Task Name",
    "query": {
     "query": "label_values(flink_taskmanager_job_task_isBackPressured{job_name=~\"$job_name\"},task_name)"
    }
   },
   { "name": "ad_hoc", "label": "Ad Hoc" }
  ]
 },
 "panels": [
  { "title": "Job Manager (JVM - CPU)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "flink_k8soperator_Status_JVM_CPU_Load{job=\"processing/flink-operator\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "delta(flink_k8soperator_Status_JVM_CPU_Time{job=\"processing/flink-operator\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_k8soperator_Status_JVM_Threads_Count{job=\"processing/flink-operator\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Job Manager (JVM - Memory Usage)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_k8soperator_Status_JVM_Memory_Heap_Used{job=\"processing/flink-operator\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_k8soperator_Status_JVM_Memory_NonHeap_Used{job=\"processing/flink-operator\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Direct",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_k8soperator_Status_JVM_Memory_Direct_MemoryUsed{job=\"processing/flink-operator\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mapped",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_k8soperator_Status_JVM_Memory_Mapped_MemoryUsed{job=\"processing/flink-operator\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_k8soperator_Status_JVM_Memory_Metaspace_Used{job=\"processing/flink-operator\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Job Manager (JVM - Garbage Collector)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }
  },
  {
   "title": "Garbage Collector Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_k8soperator_Status_JVM_GarbageCollector_All_Time",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Scavenge Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(flink_k8soperator_Status_JVM_GarbageCollector_All_Time[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Task Manager (JVM - CPU)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_CPU_Load{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "delta(flink_taskmanager_Status_JVM_CPU_Load{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Threads_Count{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "Task Manager (JVM - Memory Usage)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 }
  },
  {
   "title": "Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Used{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "Direct",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Direct_MemoryUsed{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "Mapped",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Mapped_MemoryUsed{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Metaspace_Used{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "Task Manager (Memory - Shuffle Netty)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 }
  },
  {
   "title": "Total Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_Shuffle_Netty_TotalMemory{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "Total Memory Segments",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_Shuffle_Netty_TotalMemorySegments{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_Shuffle_Netty_UsedMemory{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_Shuffle_Netty_AvailableMemory{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "Idle Time Ms (per Second)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_idleTimeMsPerSecond{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Is Back Pressured",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 81 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_isBackPressured{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Task Manager  (Job Task - General)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 }
  },
  {
   "title": "Number Buffers in Local",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numBuffersInLocal{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Number Buffers in Local (per Second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_numBuffersInLocalPerSecond{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Number Buffers Out (per Second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_numBuffersOutPerSecond{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Bytes In Local (per Second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_numBytesInLocalPerSecond{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Number Buffers Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "delta(flink_taskmanager_job_task_numBuffersOutPerSecond{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Bytes Out (per Second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_numBytesOutPerSecond{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(flink_taskmanager_job_task_numBytesIn{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Bytes In (per Second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_numBytesInPerSecond{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Records Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "delta(flink_taskmanager_job_task_numRecordsOut{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Bytes Out (per Second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_numRecordsOutPerSecond{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(flink_taskmanager_job_task_numBytesOut{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Records In",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "delta(flink_taskmanager_job_task_numRecordsIn{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Task Manager (Job Task - Buffers)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 }
  },
  {
   "title": "In Pool Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 128 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_buffers_inPoolUsage{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Input Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 128 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_buffers_inputQueueLength{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Out Pool Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 128 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_buffers_outPoolUsage{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Output Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 128 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_buffers_outputQueueLength{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Task Manager (Job Task - Operator)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 }
  },
  {
   "title": "Number Records In",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(flink_taskmanager_job_task_operator_numRecordsIn{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Number Records Out (per Second)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_operator_numRecordsInPerSecond{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Number Records In",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 139 },
   "targets": [
    {
     "expr": "delta(flink_taskmanager_job_task_operator_numRecordsOut{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Num Records Out (per Second)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 139 },
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Task Manager (Job Task - Shuffle Netty)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 }
  },
  {
   "title": "Input Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_inputQueueLength{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Output Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_Shuffle_Netty_Output_Buffers_outputQueueLength{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Input Number Buffers In Local",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_numBuffersInLocal{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Out Pool Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_Shuffle_Netty_Output_Buffers_outPoolUsage{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Input Floating Buffers Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_inputFloatingBuffersUsage{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Input Num Buffers In Remote (per Second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_Shuffle_Netty_Input_numBuffersInRemotePerSecond{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Input Num Bytes In Local",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(flink_taskmanager_job_task_Shuffle_Netty_Input_numBytesInLocal{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Input Number Buffers In Local (per Second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_Shuffle_Netty_Input_numBuffersInLocalPerSecond{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Input Number Buffers In Remote",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_numBuffersInRemote{job=\"processing/flink-taskmanager\"}",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Input Number Bytes In Remote (per Second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_Shuffle_Netty_Input_numBytesInRemotePerSecond{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Input Number Bytes In Local (per Second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_Shuffle_Netty_Input_numBytesInLocalPerSecond{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  },
  {
   "title": "Input Number Bytes In Remote",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(flink_taskmanager_job_task_Shuffle_Netty_Input_numBytesInRemote{job=\"processing/flink-taskmanager\"}[1m])",
     "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
    }
   ]
  }
 ]
}