{
 "title": "Trino",
 "description": "Trino deploy on k8s, collect jmx to monitor worker and master",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "jvm memory(used)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{area}}"
    }
   ]
  },
  {
   "title": "jvm memory(committed)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{area}}"
    }
   ]
  },
  {
   "title": "jvm memory pool(used)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{pool}}"
    }
   ]
  },
  {
   "title": "jvm memory pool(committed)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_committed{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{pool}}"
    }
   ]
  },
  {
   "title": "jvm buffer pool(used)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_pool_used_bytes{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{pool}}"
    }
   ]
  },
  {
   "title": "jvm buffer pool(capacity)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_pool_capacity_bytes{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{pool}}"
    }
   ]
  },
  { "title": "JVM Thread", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": " Number of threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Number of threads in deadlock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_deadlocked{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Thread state distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_state{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{state}}"
    }
   ]
  },
  { "title": "OperatingSystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Open File Descriptor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Average CPU Usage (1min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(java_lang_OperatingSystem_ProcessCpuTime{job=\"processing/trino\"}[1m]) / (java_lang_OperatingSystem_AvailableProcessors{job=\"processing/trino\"} * 60 * 1000000000)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Cpu Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_CpuLoad{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Cpu Load(Process)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Cpu Load(System)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemCpuLoad{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemLoadAverage{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Free Memory Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_FreeMemorySize{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Free Physical Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_FreePhysicalMemorySize{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "SqlTaskManager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Volume Input Data SQL Tasks (1min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(trino_execution_SqlTaskManager_InputDataSize_TotalCount{job=\"processing/trino\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Amount of Data produced by Tasks SQL (1min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(trino_execution_SqlTaskManager_OutputDataSize_TotalCount{job=\"processing/trino\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "SQL Tasks failures (1min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(trino_execution_SqlTaskManager_FailedTasks_TotalCount{job=\"processing/trino\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "TaskExecutor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Number of threads in the thread pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "trino_execution_RemoteTaskFactory_Executor_PoolSize{job=\"processing/trino\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of tasks in the TaskExecutor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "trino_execution_RemoteTaskFactory_Executor_TaskCount{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "ThriftMetastoreStats(One Minute)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 }
  },
  {
   "title": "Number of failed calls (io_trino_plugin)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetAllDatabases_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetAllDatabases"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetDatabase_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetDatabase"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetAllTables_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetAllTables"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetTablesWithParameter_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetTablesWithParameter"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetAllViews_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetAllViews"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetTable_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetTable"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetFields_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetFields"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetTableColumnStatistics_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetTableColumnStatistics"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_SetTableColumnStatistics_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-SetTableColumnStatistics"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_DeleteTableColumnStatistics_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-DeleteTableColumnStatistics"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetPartitionColumnStatistics_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetPartitionColumnStatistics"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_SetPartitionColumnStatistics_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-SetPartitionColumnStatistics"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_DeletePartitionColumnStatistics_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-DeletePartitionColumnStatistics"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetPartitionNames_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetPartitionNames"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetPartitionNamesByParts_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetPartitionNamesByParts"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetPartition_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetPartition"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetPartitionsByNames_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetPartitionsByNames"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_CreateDatabase_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-CreateDatabase"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_DropDatabase_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-DropDatabase"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AlterDatabase_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-AlterDatabase"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_CreateTable_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-CreateTable"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_DropTable_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-DropTable"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AlterTable_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-AlterTable"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AddPartitions_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-AddPartitions"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_DropPartition_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-DropPartition"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AlterPartition_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-AlterPartition"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AcquireLock_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-AcquireLock"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_CheckLock_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-CheckLock"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_Unlock_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-Unlock"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AlterPartitions_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-AlterPartitions"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AddDynamicPartitions_TotalFailures_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-AddDynamicPartitions"
    }
   ]
  },
  {
   "title": " Number of failed calls (ThriftExceptions) (io_trino_plugin)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetAllDatabases_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetAllDatabases"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetDatabase_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetDatabase"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetAllTables_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetAllTables"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetTablesWithParameter_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetTablesWithParameter"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetAllViews_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetAllViews"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetTable_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetTable"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetFields_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetFields"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetTableColumnStatistics_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetTableColumnStatistics"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_SetTableColumnStatistics_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-SetTableColumnStatistics"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_DeleteTableColumnStatistics_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-DeleteTableColumnStatistics"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetPartitionColumnStatistics_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetPartitionColumnStatistics"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_SetPartitionColumnStatistics_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-SetPartitionColumnStatistics"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_DeletePartitionColumnStatistics_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-DeletePartitionColumnStatistics"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetPartitionNames_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetPartitionNames"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetPartitionNamesByParts_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetPartitionNamesByParts"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetPartition_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetPartition"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetPartitionsByNames_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetPartitionsByNames"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_CreateDatabase_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-CreateDatabase"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_DropDatabase_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-DropDatabase"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AlterDatabase_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-AlterDatabase"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_CreateTable_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-CreateTable"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_DropTable_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-DropTable"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AlterTable_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-AlterTable"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AddPartitions_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-AddPartitions"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_DropPartition_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-DropPartition"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AlterPartition_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-AlterPartition"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AcquireLock_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-AcquireLock"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_CheckLock_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-CheckLock"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_Unlock_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-Unlock"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AlterPartitions_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-AlterPartitions"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AddDynamicPartitions_ThriftExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-AddDynamicPartitions"
    }
   ]
  },
  {
   "title": "Number of failed calls (MetastoreExceptions) (io_trino_plugin)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetAllDatabases_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetAllDatabases"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetDatabase_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetDatabase"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetAllTables_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetAllTables"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetTablesWithParameter_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetTablesWithParameter"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetAllViews_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetAllViews"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetTable_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetTable"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetFields_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetFields"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetTableColumnStatistics_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetTableColumnStatistics"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_SetTableColumnStatistics_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-SetTableColumnStatistics"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_DeleteTableColumnStatistics_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-DeleteTableColumnStatistics"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetPartitionColumnStatistics_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetPartitionColumnStatistics"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_SetPartitionColumnStatistics_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-SetPartitionColumnStatistics"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_DeletePartitionColumnStatistics_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-DeletePartitionColumnStatistics"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetPartitionNames_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetPartitionNames"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetPartitionNamesByParts_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetPartitionNamesByParts"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetPartition_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetPartition"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetPartitionsByNames_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-GetPartitionsByNames"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_CreateDatabase_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-CreateDatabase"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_DropDatabase_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-DropDatabase"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AlterDatabase_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-AlterDatabase"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_CreateTable_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-CreateTable"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_DropTable_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-DropTable"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AlterTable_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-AlterTable"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AddPartitions_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-AddPartitions"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_DropPartition_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-DropPartition"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AlterPartition_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-AlterPartition"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AcquireLock_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-AcquireLock"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_CheckLock_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-CheckLock"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_Unlock_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-Unlock"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AlterPartitions_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-AlterPartitions"
    },
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AddDynamicPartitions_MetastoreExceptions_OneMinute_Count{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-AddDynamicPartitions"
    }
   ]
  },
  {
   "title": "The average time taken by CreateTable.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_CreateTable_Time_OneMinute_Avg{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-io_trino_plugin"
    },
    {
     "expr": "trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_CreateTable_Time_OneMinute_Avg{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-plugin"
    }
   ]
  },
  {
   "title": "Maximum time taken by GetAllDatabases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetAllDatabases_Time_OneMinute_Max{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-io_trino_plugin"
    },
    {
     "expr": "trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetAllDatabases_Time_OneMinute_Max{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-plugin"
    }
   ]
  },
  {
   "title": "Average time taken by GetDatabase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetDatabase_Time_OneMinute_Avg{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-io_trino_plugin"
    },
    {
     "expr": "trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetDatabase_Time_OneMinute_Avg{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-plugin"
    }
   ]
  },
  {
   "title": "Maximum time taken by GetDatabase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetDatabase_Time_OneMinute_Max{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-io_trino_plugin"
    },
    {
     "expr": "trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetDatabase_Time_OneMinute_Max{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-plugin"
    }
   ]
  },
  {
   "title": "The average time taken by AlterTable.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AlterTable_Time_OneMinute_Avg{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-io_trino_plugin"
    },
    {
     "expr": "trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AlterTable_Time_OneMinute_Avg{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-plugin"
    }
   ]
  },
  {
   "title": "The maximum time taken by CreateTable.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_CreateTable_Time_OneMinute_Max{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-io_trino_plugin"
    },
    {
     "expr": "trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_CreateTable_Time_OneMinute_Max{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-plugin"
    }
   ]
  },
  {
   "title": "Average time taken by GetTable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetTable_Time_OneMinute_Avg{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-io_trino_plugin"
    },
    {
     "expr": "trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetTable_Time_OneMinute_Avg{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-plugin"
    }
   ]
  },
  {
   "title": "Maximum time taken by GetTable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetTable_Time_OneMinute_Max{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-io_trino_plugin"
    },
    {
     "expr": "trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_GetTable_Time_OneMinute_Max{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-plugin"
    }
   ]
  },
  {
   "title": "The average time taken by AcquireLock.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AcquireLock_Time_OneMinute_Avg{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-io_trino_plugin"
    },
    {
     "expr": "trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AcquireLock_Time_OneMinute_Avg{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-plugin"
    }
   ]
  },
  {
   "title": "The maximum time taken by AlterTable.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AlterTable_Time_OneMinute_Max{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-io_trino_plugin"
    },
    {
     "expr": "trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AlterTable_Time_OneMinute_Max{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-plugin"
    }
   ]
  },
  {
   "title": "The maximum time taken by AcquireLock.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AcquireLock_Time_OneMinute_Max{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-io_trino_plugin"
    },
    {
     "expr": "trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_AcquireLock_Time_OneMinute_Max{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-plugin"
    }
   ]
  },
  {
   "title": "The maximum time taken by Unlock.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "io_trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_Unlock_Time_OneMinute_Max{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-io_trino_plugin"
    },
    {
     "expr": "trino_plugin_hive_metastore_thrift_ThriftHiveMetastore_Unlock_Time_OneMinute_Max{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-plugin"
    }
   ]
  },
  {
   "title": "FileFormatDataSourceStats(One Minute)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 }
  },
  {
   "title": "ReadBytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "io_trino_plugin_hive_FileFormatDataSourceStats_ReadBytes_OneMinute_Total{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-io_trino_plugin"
    },
    {
     "expr": "trino_plugin_hive_FileFormatDataSourceStats_ReadBytes_OneMinute_Total{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-plugin"
    }
   ]
  },
  {
   "title": "The average read time from 100KB to 1MB.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "io_trino_plugin_hive_FileFormatDataSourceStats_100KBto1MB_OneMinute_Avg{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-io_trino_plugin"
    },
    {
     "expr": "trino_plugin_hive_FileFormatDataSourceStats_100KBto1MB_OneMinute_Avg{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-plugin"
    }
   ]
  },
  {
   "title": "The average read time from 0B to 100KB.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "io_trino_plugin_hive_FileFormatDataSourceStats_0Bto100KB_OneMinute_Avg{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-io_trino_plugin"
    },
    {
     "expr": "trino_plugin_hive_FileFormatDataSourceStats_0Bto100KB_OneMinute_Avg{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-plugin"
    }
   ]
  },
  {
   "title": "The maximum read time from 0B to 100KB.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "io_trino_plugin_hive_FileFormatDataSourceStats_0Bto100KB_OneMinute_Max{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-io_trino_plugin"
    },
    {
     "expr": "trino_plugin_hive_FileFormatDataSourceStats_0Bto100KB_OneMinute_Max{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-plugin"
    }
   ]
  },
  {
   "title": "The maximum read time from 100KB to 1MB.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "io_trino_plugin_hive_FileFormatDataSourceStats_100KBto1MB_OneMinute_Max{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-io_trino_plugin"
    },
    {
     "expr": "trino_plugin_hive_FileFormatDataSourceStats_100KBto1MB_OneMinute_Max{job=\"processing/trino\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{name}}-plugin"
    }
   ]
  }
 ]
}