{
 "title": "Spark Operator",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Spark Driver CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{pod=~\"spark-.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM NoHeap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=~\"processing/spark-job\", area=~\"nonheap\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Operator Controller CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{namespace=~\"processing\",pod=~\"spark-operator-controller.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Executor CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{namespace=~\"processing\",pod=~\"spark-.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"spark.*\"}) /sum (machine_memory_bytes{node=~\".*\"}) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Operator Webhook CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{namespace=~\"processing\",pod=~\"spark-operator.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Executor Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=~\"processing\"} /1024 /1024",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "SparkApplication and Executors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Submitted SparkApplications",
   "type": "stat",
   "description": "Total number of SparkApplication submitted by the Operator.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_application_submit_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running SparkApplications",
   "type": "stat",
   "description": "Total number of SparkApplication which are currently running.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_application_running_count{job=\"processing/spark-operator\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Succ. Completed Spark Executors",
   "type": "stat",
   "description": "Total number of Spark Executors which completed successfully.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_success_count{job=\"processing/spark-operator\"})"
    }
   ]
  },
  {
   "title": "Failed Spark Executors",
   "type": "stat",
   "description": "Total number of Spark Executors which failed.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_failure_count{job=\"processing/spark-operator\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed SparkApplications",
   "type": "stat",
   "description": "Total number of SparkApplication which failed to complete.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_application_failure_count{job=\"processing/spark-operator\"})"
    }
   ]
  },
  {
   "title": "Succ. completed SparkApplications.",
   "type": "stat",
   "description": "Total number of SparkApplication which completed successfully.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_application_success_count{job=\"processing/spark-operator\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "SparkApplication Work Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Adds per sec handled by work queue",
   "type": "timeseries",
   "description": "Total number of adds handled by work queue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "workqueue_adds_total{job=~\"processing/spark-operator\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "spark_app_start_latency_seconds_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(spark_application_start_latency_seconds_histogram_bucket{job=\"processing/spark-operator\"}[5m]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "histogram_quantile(0.75, rate(spark_application_start_latency_seconds_histogram_bucket{job=\"processing/spark-operator\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.65, rate(spark_application_start_latency_seconds_histogram_bucket{job=\"processing/spark-operator\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retries handled by work queue",
   "type": "timeseries",
   "description": "Total number of retries handled by work queue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(workqueue_retries_total{job=~\"processing/spark-operator\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "average spark_app_start_latency_microseconds_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(spark_application_start_latency_seconds_sum{job=\"processing/spark-operator\"}[5m])/rate(spark_application_start_latency_seconds_count{job=\"processing/spark-operator\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}