# Customizacao dos plugins:
#     https://kestra.io/docs/installation/docker#build-a-custom-docker-image

# ARG IMAGE_TAG=latest-no-plugins
# FROM kestra/kestra:$IMAGE_TAG

# RUN /app/kestra plugins install \
#   io.kestra.plugin:plugin-notifications:LATEST \
#   io.kestra.storage:storage-gcs:LATEST \
#   io.kestra.plugin:plugin-gcp:LATEST