apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@github.com:owshq-plumbers/trn-mst-bdk-2-0.git'
    path: 01-infra/src/helm-charts/learning/mlflow
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
      namespace: learning
      server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PruneLast=true